### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by mr-feek** [noraesae/perfect-scrollbar-bower#1]
History was rewritten and so were the accompanying git tags -- now anyone who had been relying on the likes of `0.6.12` cannot build.

components/perfect-scrollbar/js/perfect-scrollbar.jquery doesn't exist anymore, wheras it used to in the previous `0.6.12`

I resolved by using a fork with the previous 0.6.12, but others will also run into this issue

**Comment by victorsoliveira** [comment]
Hi, this user and repository was deleted. I'm not the "noraesae", i just create it again to mantain compatibility with my system that uses this library.

**Comment by jairoandre** [comment]
Any reason for the deletion? This just broke one of my build pipeline. XD
Also, thanks for recreate this. (pls dont delete it).

**Comment by kdela** [comment]
Good to see I'm not alone XD
I've created PR with version 0.6.14 If someone is interested.
https://github.com/noraesae/perfect-scrollbar-bower/pull/2

It's also possible to install it from my private fork, and I promise to not delete it
> bower install git@github.com:kdela/perfect-scrollbar-bower.git --save

**Comment by MrPetovan** [comment]
Hi, I think reusing the same GitHub user name is misleading and wrong, please move this outdated version repository to your own account. Bower and npm package have to be deprecated.

**Comment by mr-feek** [comment]
Couldn't agree more @MrPetovan

**Comment by medb** [comment]
May you fork https://github.com/dorilla/perfect-scrollbar-bower repo in-place of this repo? It will fix more builds, because this fork has more releases in it.

**Comment by victorsoliveira** [comment]
@MrPetovan What is the new and correct repository for perfect-scrollbar ?

**Comment by MrPetovan** [comment]
According to https://bower.io/docs/creating-packages/ it could just be `victorsoliveira/perfect-scrollbar` (once you create it in GitHub) in your `"dependencies"` list.

**Comment by NielsHolt** [comment]
It appears that perfect-scrollbar was moved to https://github.com/mdbootstrap/perfect-scrollbar

**Comment by victorsoliveira** [comment]
@mr-feek @MrPetovan Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.

Thanks!

**Comment by MrPetovan** [comment]
> It appears that perfect-scrollbar was moved to https://github.com/mdbootstrap/perfect-scrollbar

Thanks, I looked into it but it isn't a drop-in replacement, it doesn't have the jQuery bindings for example.

**Comment by aryehb** [comment]
>Thanks, I looked into it but it isn't a drop-in replacement, it doesn't have the jQuery bindings for example.

If you use the same version numbers, it should be exactly the same.

**Comment by MrPetovan** [comment]
Ooooh, I didn't think about that, thank you so much!

**Comment by ViniciusFXavier** [comment]
> @mr-feek @MrPetovan Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.
> 
> Thanks!

Read: https://github.com/noraesae/perfect-scrollbar-bower/issues/5
