### ISSUE TITLE
Demo 404

### ISSUE THREAD

**Issue by MX-Qulin** [noraesae/perfect-scrollbar-bower#3]
Well, It seems that Demo goes 404 Error.
I can't see the performence of this project.
Would you please fix it or take a ScreenShot to let me view how it looks like?
Thank you:)

**Comment by victorsoliveira** [comment]
Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.

Thanks!

**Comment by ViniciusFXavier** [comment]
> Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.
> 
> Thanks!

Read: https://github.com/noraesae/perfect-scrollbar-bower/issues/5
