### ISSUE TITLE
perfect-scrollbar version（0.6.16） problem

### ISSUE THREAD

**Issue by gengzuoyu** [noraesae/perfect-scrollbar-bower#4]
I used version 0.6.16 before, but when I execute the 'brower install' command ，it told me that tag was not found today. then ,I tried to use the old version 0.6.12, but were told that the file perfecr-scrollbar.min.js was missing. So, what happended? how to solve this problem?

**Comment by gengzuoyu** [comment]
Who has the 0.6.16 version of the code？

**Comment by saloumfall** [comment]
I have the same problem

**Comment by ViniciusFXavier** [comment]
Alternative: https://github.com/FieldControl/perfect-scrollbar-bower

**Comment by gengzuoyu** [comment]
I modified the file of bower.json，and it works. 
"dependencies": {
   ...
"perfect-scrollbar": "git@github.com:FieldControl/perfect-scrollbar-bower.git#v0.6.16",
   ...
}

**Comment by gengzuoyu** [comment]
The perfect-scrollbar in bower specifies the default git address "https://github.com/noraesae/perfect-scrollbar-bower".  if the code which in 'https://github.com/FieldControl/perfect-scrollbar-bower' can be committed into noraesae repository and also set 0.6.16 version，users will not have to modify the version of perfect-scrollbar in brower.json. That may be better.

**Comment by victorsoliveira** [comment]
Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.

Thanks!

**Comment by gengzuoyu** [comment]
I tried https://github.com/mdbootstrap/perfect-scrollbar repository，but failed（ no such file 'perfect-scrollbar.min.js'） in my project, no matter v0.6.16 or v1.5.0(lastest version).  The https://github.com/FieldControl/perfect-scrollbar-bower is ok.

**Comment by ViniciusFXavier** [comment]
> Use https://github.com/mdbootstrap/perfect-scrollbar repository, i will delete this repository as soon as possible.
> 
> Thanks!

Read: https://github.com/noraesae/perfect-scrollbar-bower/issues/5
